[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tensor_utils"
version = "0.1.0"
description = "A running collection of reusable Python utilities for tensor analysis."
authors = [
    { name = "Pushkar Agrawal", email = "pushkar5586@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
keywords = ["utilities", "decorators", "timing"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache License 2.0",
    "Operating System :: OS Independent",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "ruff>=0.1.0"
]

[tool.setuptools.packages.find]
where = ["src"]